apiVersion: apps/v1
kind: Deployment

metadata:
  name: wordpress-deployment

spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: ihapp
    spec:
      containers:
        - name: ihapp
          image: wordpress
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: MYSQL_ROOT_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: ihapp-config
                  key: MYSQL_DATABASE
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ihapp-config
                  key: MYSQL_HOST
            - name:  WORDPRESS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ihapp-config
                  key:  WORDPRESS_DB_USER
           
           
           
  
  selector:
    matchLabels:
      component: ihapp


      